server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://47.96.143.200:27017
      database: xc_cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0