server:
  port: 40100
spring:
  application:
    name: xc-service-search
xuecheng:
  elasticsearch:
    hostlist: ${eshostlist:127.0.0.1:9200}
    course:
      index: xc_course
      type: doc
      sourse_filed:
        id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_ time,start_time,end_time
